spring.application.name=Trip10

spring.datasource.url=jdbc:mysql://localhost:3306/trip10
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

jwt.secret=nzZ5OBW7QN0igePVaHyFoM2k8A6gy0RDbbwhU2CSbHM=
